### ISSUE TITLE
通知を音声で読み上げる機能の実装。

### ISSUE THREAD

**Issue by StoneDot** [jphacks/TH_1601#1]

**Comment by fuurin** [comment]
http://qiita.com/Tama_maru/items/2fc27f796151f2e61cbd
に従って、LINE通知をダイアログか何かで出力できるようにする。

Text To Speechで音声を出力する。
(他に良いのがあればそっち)

**Comment by fuurin** [comment]
LINEに関してはDONE

**Comment by StoneDot** [comment]
APIバージョンが19にあがっていたのですが何か意図合ってのことでしょうか？

**Comment by StoneDot** [comment]
18に戻しておきました。
