### ISSUE TITLE
句点位置学習用データの準備。

### ISSUE THREAD

**Issue by StoneDot** [jphacks/TH_1601#2]

**Comment by noimin0610** [comment]
twitterは顔文字・アスキーアート等文章の形式が自由すぎてデータの整形に時間がかかるので，
文章として成立していてかつ話し言葉に近い，アマチュアweb小説サイトからスクレイピングした台詞データを使ってデータを作成しました．
このデータを使って，SVMを用いた学習を行う予定です．

**Comment by noimin0610** [comment]
データの整備自体は完了しました．句点挿入プログラムを作成中です．
