### ISSUE TITLE
現在登録されている自分の友だちをAndroidで表示する

### ISSUE THREAD

**Issue by StoneDot** [jphacks/TH_1601#25]

**Comment by StoneDot** [comment]
4786d75 でサーバー側の実装完了。

**Comment by fuurin** [comment]
private void replaceFragment(Fragment fragment) {
        FragmentTransaction transaction = mFM.beginTransaction();
        transaction.replace(R.id.main_screen, fragment);
        transaction.addToBackStack(null);
        transaction.commit();
        mFM.executePendingTransactions();
    }

**Comment by fuurin** [comment]
mFMは、Activity.getSupportFragmentManagerで取得

**Comment by StoneDot** [comment]
エンドポイント：
/users/friend_list

渡すJSON：
”mid" => 送り手ユーザーのMID

帰ってくるJSON：
{ "friend_list" : [{
"display_name" => user.display_name,
"user_id" => user.user_id,
 "picture_url" => user.picture_url
},
... // 複数のフレンドがいる場合はこれが続く。
]}
