### ISSUE TITLE
画面がアクティブなときは音声読み上げをしない設定

### ISSUE THREAD

**Issue by StoneDot** [jphacks/TH_1601#32]
画面がアクティブなときはわざわざ読み上げたりしない設定があったほうが良い。

**Comment by noimin0610** [comment]
「スマホ起動時は読み上げをしない」というチェックボックスのON/OFFをpreferenceで保存するところまでやりました（ブランチ名：preference）

**Comment by noimin0610** [comment]
MainActivityでチェック情報をisNotReadに読み込むところまで書きました．
あとはisNotReadを使って分岐させるだけ

**Comment by StoneDot** [comment]
実装できます？

**Comment by StoneDot** [comment]
わたしが寝てしまったので、テストが出来ないからmasterへの取り込みとテストはきつそう。朝早く起きて、もし実装するという場合はスラックかラインで声かけて下さい。

**Comment by noimin0610** [comment]
時間と技術的にきついですね．
今回は見送りましょう．
