### ISSUE TITLE
最終的なリポジトリのフォーク＆DEVPOSTへの反映

### ISSUE THREAD

**Issue by noimin0610** [jphacks/TH_1601#42]

**Comment by StoneDot** [comment]
DEVPOSTに投稿したURLをこちらにも張ってもらえるとありがたいです。

**Comment by StoneDot** [comment]
Master に apk ファイルを追加しておきました。一応これが Release Candidate になりますね。

**Comment by noimin0610** [comment]
今からfolkしてDEVPOST更新します！

**Comment by noimin0610** [comment]
https://devpost.com/software/smartwalk-pin9w6
DEVPOSTのURLです．
ご確認お願いします．

**Comment by StoneDot** [comment]
『安全上の問題を解決したの歩きスマホの有用な活用法を提案するシステムである．』
これ誤字ですかね。

**Comment by StoneDot** [comment]
準備のところで、SmartWalkのメニューから『LINEにログイン』をクリックしてLINEの認証をする必要がありますね。

**Comment by StoneDot** [comment]
取り敢えずそこら辺、こっちのリポジトリで書き換えておきます。

**Comment by noimin0610** [comment]
誤字は修正しました．
準備のところも書き換え次第，フォークしたリポジトリのほうも追従させます．

**Comment by StoneDot** [comment]
READMEに加筆しました。

**Comment by noimin0610** [comment]
フォーク先も更新しました．

**Comment by StoneDot** [comment]
わたしが確認した範囲では他に気になる点はありませんでした。

**Comment by StoneDot** [comment]
特に何もなければ今のMasterにタグつけて、こちらのリポジトリでもリリースという形にしておきます。

**Comment by noimin0610** [comment]
おっけーです！

**Comment by StoneDot** [comment]
作業終えました。多分、オンライン審査に向けた準備はこれで完了ですね。
お疲れ様です。

**Comment by noimin0610** [comment]
お疲れ様でした！
あとは審査を待つのみですね。
