### ISSUE TITLE
LINEのAPIの試験利用

### ISSUE THREAD

**Issue by noimin0610** [jphacks/TH_1601#6]

**Comment by StoneDot** [comment]
アプリから直接返信はどうやっても無理っぽいので、代理返事用の適当なBOTを作ります。

**Comment by StoneDot** [comment]
BOT経由ならばPushでメッセージ送れることを確認しました。
動かすためには送り先の人のIDが必要で、公開リポジトリに登録するのは危険なため、
当日テスト用のスクリプトを渡します。
本番までに、表示名から送り先の人のIDを特定する方法を考える必要があるかもしれません。
